### ISSUE TITLE
ft_fill 오버플로우 발견

### ISSUE THREAD

**Issue by 3Cat-jaguar** [Y-in-Y/ylee#1]
프롬프트에 내용 마지막에 스페이스로 끝나는 경우 ft_fill 처리할 때 오버플로우 발생됩니다.

cnt 개수는 마지막에 있는 스페이스가 나오기 전까지로 잘 읽어서 char 이중배열을 만드는데

ft_fill 에서 값을 넣을때 스페이스 뒤에 다른 문자가 있을것으로 생각하고 말록된 영역 밖까지 찾는 것 같습니다.

이 케이스에 대해서 인덱스 체크 부탁드려요~

**Comment by Inju-Yang** [comment]
확인하고 체크 하겠습니다~

**Comment by 3Cat-jaguar** [comment]
해결완료
